src/css/Parser.js, tests/css/Parser.js
This (note whitespace around `max-width: 710px`) should be valid:
```css
@media screen and ( max-width: 710px ) {}
```
Currently the whole line errors out:
```
[L1:C20]
>> ERROR: Expected IDENT at line 1, col 20. This rule looks for recoverable syntax errors. (errors) Browsers: All
[L1:C32]
>> ERROR: Expected LBRACE at line 1, col 32. This rule looks for recoverable syntax errors. (errors) Browsers: All
[L1:C32]
>> ERROR: Unexpected token '710px' at line 1, col 32. This rule looks for recoverable syntax errors. (errors) Browsers: All
[L1:C38]
>> ERROR: Unexpected token ')' at line 1, col 38. This rule looks for recoverable syntax errors. (errors) Browsers: All
[L1:C40]
>> ERROR: Unexpected token '{' at line 1, col 40. This rule looks for recoverable syntax errors. (errors) Browsers: All …
```
=> Allow spaces within media query features

src/css/Parser.js, src/css/TokenStream.js, src/css/Tokens.js, tests/css/CSSParserTests.htm, tests/css/CSSTokensTests.htm, tests/css/Parser.js, tests/css/TokenStream.js
=> Add support for @document, @-moz-document

src/css/Properties.js, src/css/ValidationTypes.js
[Fix #104] Add support for `font-feature-settings`
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
=> [Fix #104] Add support for `font-feature-settings`

src/css/Properties.js
Add support for non-prefixed `box-decoration-break`
https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break
=> Add support for box-decoration-break non-prefixed

src/util/StringReader.js
[Fix #133] StringReader fails to normalize Windows line endings
`\r` matches a carriage return
`\n` matches a newline character.
`{1, 2}` matches between either 1 or 2 of the preceding tokens
This way you can start with either and should cover both linux or windows to fix #133
cc: @nschonni
=> [Fix #133] StringReader fails to normalize Windows line endings

src/css/Colors.js
=> Add missing currentColor keyword

tests/css/Validation.js
This was inadvertently broken in commit 8aa0a077129528fbbc4b73901581470c1438cf5f.
=> Add missing comma to fix a test case.

src/css/TokenStream.js, tests/css/Parser.js, tests/css/TokenStream.js
This is an updated version of PR #16.  In addition, the parsing of escape sequences in identifiers is fixed to match https://www.w3.org/TR/CSS21/grammar.html#scanner
In particular, don't accept `"\\\r"` as a valid escape sequence, and swallow trailing space for every hex escape (not just 2-digit ones).
We also tweak `readName` in the tokenizer to unescape the names it reads, which makes `@ch\041 rset` correctly parse as a `CHARSET_SYM`.
Finally, the set of "nonascii" characters is changed to match the spec -- the lower bound is raised from `\u0080` to `\u00A0`.
=> Strictly parse whitespace and escapes.

build.xml
This prevents spurious errors in the YUI test suite on Java implementations with a small default stack size.
Fixes: #136
=> Increase Java runtime stack size when running tests.

src/css/Properties.js, src/css/ValidationTypes.js, tests/css/Validation.js
The clip property has has browser support for a long time, and even parser-lib was nearly there. The clip property is now deprecated, and its successor clip-path is more versatile, the use cases are much more credible. Also support for the clip-rule propery. The properties can be used without support of a svg file.
See: https://drafts.fxtf.org/css-masking-1/#the-clip-path
This is a rebased and squashed version of PR #160.
=> Support clip properties.

src/util/SyntaxError.js
This ensures that the superclass constructor is called and the `name` property is set appropriately.
Fixes: #168, #169.
=> Make SyntaxError properly inherit from Error.

src/css/Parser.js, tests/css/CSSParserTests.htm, tests/css/Parser.js
* Fix `line`, `col` in `"enddocument"` event.
* Support `@keyframes` inside `@document` blocks.
* Support nested `@document` blocks: `@document` inside `@document`.
* Fix `@keyframes`: consume trailing whitespace after `RBRACE`<br>All other block parsers do it, but `_keyframes()` didn't, consequently breaking the parser after `@keyframes` inside `@document` blocks.
=> Fixes for @document blocks

src/css/ValidationTypes.js, tests/css/Validation.js
This is a follow up to 17a2f0190e0670be1c1a2d9a8272080c5c7e5061, which began to enforce the non-negative value restriction on `<padding-width>` but neglected to account for the `calc()` function.
=> Allow calculated values for padding.

src/util/StringReader.js
For example, the input `\r\n\n\r` should represent three new lines. But:
```
> text = '\r\n\n\r'
> text.replace(/(\r|\n){1,2}/g, "\n");  // previous code says this is only two newlines
'\n\n'
> text.replace(/(\r\n?|\n)/g, "\n"); // this patch returns three, as expected.
'\n\n\n'
```
This PR fixes issue #155.
=> Fix line numbers when the input contains multiple sequential \n characters.

src/css/ValidationTypes.js
I've updated several simple `ValidationType` functions to show how this can be used to simplify common matchers.  It will also be used in a follow-up patch to validate the `font-variant-alternates` property which involves a large number of CSS function options.
=> Allow matching functions as literals.

src/util/TokenStreamBase.js, tests/css/TokenStream.js
This is a variant on PR #183 which also adds a test case.
=> Don't return fatal error if CSS file is empty.

src/util/StringReader.js, tests/util/StringReader.js
Previously it would read an extra character after the filter returned false.  Luckily, this function does not appear to be used (yet) anywhere else in the parser, but seems like a good idea to fix it regardless.
=> Fix the Reader#readWhile implementation.

tests/css/Parser.js, tests/css/TokenStream.js, tests/css/Validation.js, tests/util/StringReader.js
Most of these are unused variables.  There's also a for-in loop complaint (silenced) and a complaint about use of `==` (fixed).
=> tests: Fix unused variable warnings, and some other jshint complaints

src/css/Parser.js, tests/css/Parser.js
i.e. a COLON is not followed by a FUNCTION or IDENT token. e.g. `a:`. 
Fixes CSSLint/csslint#639
=> Throw SyntaxError if pseudo selector is invalid

src/css/Colors.js
While I was checking issue CSSLint/csslint#717, I've noticed some mistakes in this module and fix it to fit [CSS Color Module Level 3](https://www.w3.org/TR/css3-color/#svg-color) [Recommendation]
=> Fix colors to fit current CSS Color Module Level 3

src/css/Properties.js, tests/css/Validation.js
When I was try to find bug for issue CSSLint/csslint#718, I notice that not all valid properties for `border-image-repeat` are described. So I added `space`. Also I added tests for `border-image-repeat`.
They all passed:
```shell
✔ 'initial' is a valid value for 'border-image-repeat'
✔ 'inherit' is a valid value for 'border-image-repeat'
✔ 'unset' is a valid value for 'border-image-repeat'
✔ 'stretch' is a valid value for 'border-image-repeat'
✔ 'round stretch' is a valid value for 'border-image-repeat'
✔ 'foo' is an invalid value for 'border-image-repeat'
✔ 'round stretch foo' is an invalid value for 'border-image-repeat'
```
So parser-lib is not under suspicion =)
=> Add `space` value for `border-image-repeat`

.jshintrc, src/css/Parser.js, src/css/TokenStream.js, src/util/StringReader.js, tests/css/Parser.js, tests/css/TokenStream.js, tests/css/Validation.js
This should address [CSSLint/csslint/issues/720](https://github.com/CSSLint/csslint/issues/720).
Note: It doesn't add support for var(), only the custom properties themselves.
=> Add minimal support of CSS custom properties
