src/css/Properties.js
tests/css/Validation.js

http://www.w3.org/TR/css3-text/#text-align

Add support for new text-align values

---

src/css/Properties.js
tests/css/Validation.js

Add support for object-fit and object-position

---

src/css/ValidationTypes.js
tests/css/Validation.js

Noticed 'currentColor' wasn't being considered a valid color value. This fixes that, and adds tests for it in 'color' and adds tests for 'background-color'.

Add 'currentColor' keyword to <color>

---

src/css/Properties.js

Add support for `ime-mode`
[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/ime-mode)

Add support for `ime-mode`

---

src/css/Properties.js

[`font-kerning` MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning)
[`font-variant-position` MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position)
[`font-variant-caps` MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps)

Add additional font properties

---

src/css/PropertyValuePart.js

[Fix #131] Add support for the `fr` unit
cc: @nschonni

[Fix #131] Add support for the 'fr' unit

---

src/css/Properties.js
tests/css/Validation.js

Add support for 'vertical-align: inherit'

---

src/css/ValidationTypes.js
tests/css/CSSParserTests.htm
tests/css/Validation.js

See:
http://www.w3.org/TR/CSS21/box.html#padding-properties
http://www.w3.org/wiki/CSS/Properties/padding
This is a rebased & squashed version of PR #159.

A padding value can't be negative.

---

src/css/Properties.js
tests/css/Validation.js

This is an updated version of PR #103 that includes updated test cases.

Allow comma, background-repeat

---

src/css/Combinator.js
src/css/Parser.js
src/css/Properties.js
src/css/PropertyValueIterator.js
src/css/PropertyValuePart.js
src/css/Pseudos.js
src/css/Specificity.js
src/css/TokenStream.js
src/css/Validation.js
src/css/ValidationTypes.js
src/util/EventTarget.js
src/util/StringReader.js
src/util/TokenStreamBase.js

This is the first batch of the patches in PR #179, as requested by @XhmikosR.

Lint source code (part 1).

---

src/css/Properties.js
src/css/ValidationTypes.js
tests/css/Validation.js

See: https://drafts.fxtf.org/filters/#FilterProperty
Rebase/squash/minor improvement of #161.

Precisely validate <filter-function-list>.

---

src/css/ValidationTypes.js

A few more == tests snuck into the codebase.

Use === instead of ==.

---

src/css/Parser.js
src/css/Tokens.js
tests/css/Parser.js
tests/css/TokenStream.js

Hi
I try to give `@supports` a chance to be part of this great parser. Have a look at my code. I appreciate any feedback.
This PR addresses issue #93.

parser for @supports at rule

---

tests/css/Validation.js

Future patches will use this to add additional test cases.

Add mechanism to test invalid properties which trigger SyntaxErrors.

---

src/css/Properties.js
src/css/ValidationTypes.js
tests/css/Validation.js

Update animation-direction by adding <single-animation-direction>

---

src/css/Properties.js
tests/css/Validation.js

Added SVG properties from https://www.w3.org/TR/SVG/propidx.html which were not yet supported.

Add all remaining SVG properties

---

src/css/Parser.js
tests/css/Parser.js

I found this bug while testing for https://github.com/CSSLint/parser-lib/issues/135

allow @supports rule to be nested in @media rule

---

CONTRIBUTING.md
LICENSE

@stubbornella  as your email address is mentioned here, please have a quick look. This PR is a slightly shortened version of the CSS Lint Contributor License Agreement .

Adds CLA and updates copyright. Fixes #149

---

src/css/PropertyValuePart.js
src/css/TokenStream.js
tests/css/TokenStream.js

Definition https://developer.mozilla.org/en-US/docs/Web/CSS/angle
Fixes #216
Fixes https://github.com/CSSLint/csslint/issues/662

CSS3: Add `turn` unit to <angle> definition

---

src/css/Parser.js
tests/css/Parser.js

Description https://www.w3.org/TR/css3-conditional/#processing
Fixes #118

Parser: Support nested media queries

---

src/css/Properties.js

Spec: https://www.w3.org/TR/css-position-3/#valdef-position-sticky

Add support for position: sticky

---

src/css/Properties.js

Since there is no `auto` value, I added and adjut the following as a reference.
https://developer.mozilla.org/docs/Web/CSS/user-select

Adjust `user-select` properties vlue.

---

src/css/Colors.js

For Issue CSSLint/csslint#717
[CSS Color Module Level 4](https://drafts.csswg.org/css-color/#named-colors)

Add `rebeccapurple` to fit Named Colors of CSS Color Module Level 4

---

src/css/Properties.js
tests/css/Validation.js

Add `text-underline-position` property to fit current CSS Text Decoration Module Level 3 [CR]
[CSS Text Decoration Module Level 3](https://www.w3.org/TR/css-text-decor-3/#text-underline-position-property)

Add `text-underline-position`

---

src/css/Properties.js
src/css/ValidationTypes.js
tests/css/Validation.js

Add `mix-blend-mode` property
